name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Include this line if you have submodules
          ref: 'v2'  # Explicitly specifying the version to ensure compatibility

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Playwright
        run: |
          npx playwright install

      - name: Run Tests
        run: npm test
