name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenConnect
        run: sudo apt-get update && sudo apt-get install -y openconnect

      - name: Connect to VPN
        run: |
          sudo openconnect -u BB_QA_SRIRAM --passwd-on-stdin 124.123.26.241:8443 << EOF
          ${{ secrets.VPN_PASSWORD }}
          EOF
        env:
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run: npx playwright test loadTest --project=chromium --workers=5

      - name: Disconnect from VPN
        run: sudo pkill openconnect
