name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner here

    steps:
      - name: Connect to VPN
        run: |
          sudo openconnect -u BB_QA_SRIRAM --passwd-on-stdin 124.123.26.241:8443 << EOF
          =<zK/>8Ms9ZKnPkW
          EOF

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Playwright
        run: |
          npx playwright install

      - name: Run Tests
        run: |
          npx playwright test loadTest --project=chromium --workers=5

      - name: Disconnect from VPN
        run: sudo pkill openconnect
